import axios, { AxiosInstance } from "axios";

/**
 * Minimal Asaas v3 client — only what tenant provisioning needs: create the
 * customer, open the recurring subscription, and let the webhook (wired in
 * index.ts) flip tenant status on payment events.
 *
 * ASAAS_BASE_URL defaults to production; point it at
 * https://api-sandbox.asaas.com/v3 for testing.
 */

export interface AsaasCustomerInput {
  name: string;
  cpfCnpj: string;
  email?: string;
  mobilePhone?: string;
}

export interface AsaasSubscriptionInput {
  customerId: string;
  /** Monthly amount in BRL. */
  value: number;
  /** WEEKLY | BIWEEKLY | MONTHLY | QUARTERLY | SEMIANNUALLY | YEARLY */
  cycle?: string;
  /** BOLETO | CREDIT_CARD | PIX | UNDEFINED (customer chooses) */
  billingType?: string;
  /** yyyy-mm-dd; defaults to 7 days from now. */
  nextDueDate?: string;
  description?: string;
}

export class AsaasClient {
  private http: AxiosInstance;

  constructor(apiKey: string, baseUrl?: string) {
    let defaultUrl = "https://api.asaas.com/v3";
    if (apiKey.startsWith("$aact_hmlg_")) {
      defaultUrl = "https://api-sandbox.asaas.com/v3";
    }
    const resolvedUrl = baseUrl || process.env.ASAAS_BASE_URL || defaultUrl;
    this.http = axios.create({
      baseURL: resolvedUrl.replace(/\/+$/, ""),
      headers: { "Content-Type": "application/json", access_token: apiKey },
    });
  }

  async createCustomer(input: AsaasCustomerInput): Promise<{ id: string }> {
    try {
      const r = await this.http.post("/customers", input);
      return r.data;
    } catch (error: any) {
      this.handleError("createCustomer", error);
    }
  }

  async createSubscription(input: AsaasSubscriptionInput): Promise<{ id: string }> {
    try {
      const r = await this.http.post("/subscriptions", {
        customer: input.customerId,
        billingType: input.billingType ?? "UNDEFINED",
        value: input.value,
        cycle: input.cycle ?? "MONTHLY",
        nextDueDate: input.nextDueDate ?? defaultDueDate(),
        description: input.description ?? "Conector WhatsApp para Claude (Tzolkin)",
      });
      return r.data;
    } catch (error: any) {
      this.handleError("createSubscription", error);
    }
  }

  /**
   * One-time charge (créditos do chatbot). `externalReference` volta no
   * webhook de pagamento e é como o servidor sabe o que creditar
   * (formato: credits:<tenantId>:<qty>).
   */
  async createPayment(input: {
    customerId: string;
    value: number;
    description?: string;
    externalReference?: string;
    billingType?: string;
    dueDate?: string;
  }): Promise<{ id: string; invoiceUrl?: string }> {
    try {
      const r = await this.http.post("/payments", {
        customer: input.customerId,
        billingType: input.billingType ?? "UNDEFINED",
        value: input.value,
        dueDate: input.dueDate ?? defaultDueDate(),
        description: input.description,
        externalReference: input.externalReference,
      });
      return r.data;
    } catch (error: any) {
      this.handleError("createPayment", error);
    }
  }

  /**
   * Fetch the invoiceUrl for the first payment generated by a subscription.
   * Retorna null quando o Asaas ainda não gerou a cobrança (acontece nos
   * primeiros segundos após criar a assinatura) — não é erro.
   */
  async getPaymentUrl(subscriptionId: string): Promise<string | null> {
    try {
      const r = await this.http.get(`/subscriptions/${subscriptionId}/payments`, {
        params: { limit: 1 },
      });
      return r.data?.data?.[0]?.invoiceUrl ?? null;
    } catch (error: any) {
      this.handleError("getPaymentUrl", error);
    }
  }

  private handleError(action: string, error: any): never {
    const details = error.response?.data;
    let msg = `Asaas error during ${action}: ${error.message}`;
    if (details) msg += ` - ${JSON.stringify(details)}`;
    throw new Error(msg);
  }
}

function defaultDueDate(): string {
  const d = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);
  return d.toISOString().slice(0, 10);
}
